Update s qube tasks

diff --git a/s qube tasks b/s qube tasks
--- a/s qube tasks
+++ b/s qube tasks
@@ -33,7 +33,13 @@ suacelabs access key -- 47835e28-8668-4dd4-a03e-f28a32633730
 Register a new account in
 http://saucelabs.com/
 
-mvn clean install "-Dremote=true" "-DseleniumGridURL=http://USERNAME:47835e28-8668-4dd4-a03e-f28a32633730@ondemand.saucelabs.com:80/wd/hub"
+before change 
+mvn clean install "-Dremote=true" "-DseleniumGridURL=http://USERNAME:KEY@ondemand.saucelabs.com:80/wd/hub" 
+"-Dplatform=Windows" "-Dbrowser=Chrome" "-Dbrowserversion=51" "-Doverwrite.binaries=true"
+ 
+After change  
+ 
+mvn clean install "-Dremote=true" "-DseleniumGridURL=http://kishanadd:47835e28-8668-4dd4-a03e-f28a32633730@ondemand.saucelabs.com:80/wd/hub"
 "-Dplatform=Windows" "-Dbrowser=Chrome" "-Dbrowserversion=68" "-Doverwrite.binaries=true"
 
 
@@ -41,3 +47,39 @@ Check google chorme version on settings
 Google Chrome
 Google Chrome is up to date
 Version 68.0.3440.106 (Official Build) (64-bit)
+
+
+Gcloud Cmd line cmd
+gcloud
+gcloud auth login
+gcloud compute instances list
+gcloud compute instances create xyz
+
+
+  gcloud compute instances --image=mycentos7 --image-project=my-project-second-211910 --zone us-east1-c 
+  
+   gcloud compute instances create stu-test --image=mycentos7  --image-project=my-project-second-211910 --zone  us-east1-c 
+
+
+gcloud beta compute --project=my-project-second-211910 instances create stuwar --zone=us-east1-b 
+--machine-type=n1-standard-1 --subnet=default --network-tier=PREMIUM --maintenance-policy=MIGRATE
+--service-account=689469430753-compute@developer.gserviceaccount.com 
+--scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https:
+//www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,
+https://www.googleapis.com/auth/trace.append --image=mycentos7 
+--image-project=my-project-second-211910 --boot-disk-size=10GB --boot-disk-type=pd-standard --boot-disk-device-name=stuwar
+
+in jeckins UI
+
+
+COUNT=$(gcloud compute instances list | grep stu-test -c || true)
+if [ $COUNT -gt 0 ]; then 
+   echo "delete existing instances"
+   gcloud compute instances delete stu-test --zone us-east1-c --quiet
+fi
+COUNT=$(gcloud compute instances list | grep stu-test -c || true)
+if [ $COUNT -gt 0 ]; then 
+   echo "unable delete existing instances"
+   exit1
+fi
+gcloud compute instances create stu-test --image=mycentos7 --image-project=my-project-second-211910 --zone us-east1-c
